"""esquema_completo_inicial

Revision ID: 693d71a730c7
Revises:
Create Date: 2026-09-11 12:53:26.920160

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "693d71a730c7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column(
            "rol", sa.Enum("alumno", "profesor", "admin", name="rol_usuario"), nullable=False
        ),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "asignaturas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("prompt_redactor", sa.Text(), nullable=True),
        sa.Column("profesor_id", sa.UUID(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["profesor_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "password_set_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("usado", sa.Boolean(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "documentos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asignatura_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("ruta", sa.String(length=1024), nullable=False),
        sa.Column(
            "subido_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["asignatura_id"], ["asignaturas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matriculas",
        sa.Column("alumno_id", sa.UUID(), nullable=False),
        sa.Column("asignatura_id", sa.UUID(), nullable=False),
        sa.Column(
            "matriculado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alumno_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asignatura_id"], ["asignaturas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alumno_id", "asignatura_id"),
    )
    op.create_table(
        "mensajes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("alumno_id", sa.UUID(), nullable=False),
        sa.Column("asignatura_id", sa.UUID(), nullable=False),
        sa.Column("rol", sa.Enum("user", "assistant", name="rol_mensaje"), nullable=False),
        sa.Column("contenido", sa.Text(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("uso_rag", sa.Boolean(), nullable=False),
        sa.Column("n_iteraciones", sa.Integer(), nullable=True),
        sa.Column("latencia_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["alumno_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asignatura_id"], ["asignaturas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mensajes_alumno_asignatura", "mensajes", ["alumno_id", "asignatura_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("documento_id", sa.UUID(), nullable=False),
        sa.Column("asignatura_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column(
            "chunk_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asignatura_id"], ["asignaturas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["documento_id"], ["documentos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_chunks_asignatura_id", "document_chunks", ["asignatura_id"], unique=False
    )
    # ### end Alembic commands ###

    # Índice HNSW para el retrieval RAG (ANN por similitud coseno). No lo detecta
    # autogenerate porque no está modelado en SQLAlchemy: BGE-M3 genera vectores
    # normalizados, por lo que vector_cosine_ops es la métrica correcta.
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_document_chunks_embedding_hnsw
        ON document_chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_document_chunks_asignatura_id", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_mensajes_alumno_asignatura", table_name="mensajes")
    op.drop_table("mensajes")
    op.drop_table("matriculas")
    op.drop_table("documentos")
    op.drop_table("password_set_tokens")
    op.drop_table("asignaturas")
    op.drop_table("usuarios")
    # ### end Alembic commands ###
